### ISSUE TITLE
Environment registry

### ISSUE THREAD

**Issue by stephanebenayoun** [capsulajs/environment-registry#1]
Capsula-hub will allow to load different versions of a project/service. We need a service that will register all this versions.

The registry will contain the available versions for each project (something like "repo/package/branch": url - TO BE DEFINED).

In the future the CI/CD of each service will be able to register new versions when it runs.

```
[
	environmentKey: { 
		accessPoints: [
			{
				url: http://accessPoint/.../service1
			},
			{
				url: http://accessPoint/.../service2
			}
		]
	},
	reactive-services/feature/my-cool-feature: {...},
	master: {...},
	0.0.1: {...},
	0.0.2: {...},
]


interface Env {
	accessPoints: {
		url: string;
	}[];	
}
interface envRegistery {
	register(envKey, env: Env) : Promise<undedined>;
	environments$() : Observable<{[key:string], Env}>
}
```

**Comment by MikeSquall** [comment]
Possible to do  `environments$() : Observable<{envKey, Env}>` instead ?
